avoid warning about unused asprintf return value
some versions of gcc produce this warning, which is treated as an
error due to our conservative defaults in Makefile:

src/agent-transfer/main.c: In function ‘main’:
src/agent-transfer/main.c:676:5: error: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Werror=unused-result]
     asprintf (&alt_comment, "GnuPG keygrip %s", args.keygrip);
     ^
cc1: all warnings being treated as errors

this patch avoids the warning.